/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sara_
 */
public class PantallaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PantallaUsuario
     */
    public PantallaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jButton_registrarse = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_usuarioLogueado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_Atras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_contrasena = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_departamento = new javax.swing.JLabel();
        jLabel_puesto = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_dni = new javax.swing.JLabel();
        jTextField_contrasena = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jTextField_puesto = new javax.swing.JTextField();
        jTextField_departamento = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_dni = new javax.swing.JTextField();
        jTextField_apellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(730, 450));

        bg.setPreferredSize(new java.awt.Dimension(730, 447));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_registrarse.setBackground(new java.awt.Color(0, 51, 51));
        jButton_registrarse.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrarse.setText("Crear usuario");
        jButton_registrarse.setAlignmentY(0.0F);
        jButton_registrarse.setBorder(null);
        jButton_registrarse.setBorderPainted(false);
        jButton_registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registrarse.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bg.add(jButton_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 36));

        jButton_logout.setBackground(new java.awt.Color(0, 51, 51));
        jButton_logout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout.setText("Cerrar sesión");
        jButton_logout.setAlignmentY(0.0F);
        jButton_logout.setBorder(null);
        jButton_logout.setBorderPainted(false);
        jButton_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_logout.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bg.add(jButton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 36));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 450));

        jLabel_usuarioLogueado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_usuarioLogueado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jLabel_usuarioLogueado)
                .addGap(21, 21, 21))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 450));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Nuevo usuario");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 480, -1));

        jButton_Atras.setBackground(new java.awt.Color(0, 51, 51));
        jButton_Atras.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("Atrás");
        jButton_Atras.setBorder(null);
        jButton_Atras.setBorderPainted(false);
        jButton_Atras.setPreferredSize(new java.awt.Dimension(110, 30));
        bg.add(jButton_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_contrasena.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_contrasena.setText("Contraseña:");

        jLabel_email.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_email.setText("Email:");

        jLabel_departamento.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_departamento.setText("Departamento:");

        jLabel_puesto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_puesto.setText("Puesto:");

        jLabel_apellidos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_apellidos.setText("Apellidos:");

        jLabel_nombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_nombre.setText("Nombre:");

        jLabel_dni.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_dni.setText("DNI:");

        jTextField_contrasena.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_email.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_puesto.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_departamento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_nombre.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_dni.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jTextField_apellidos.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_email)
                            .addComponent(jLabel_dni)
                            .addComponent(jLabel_apellidos)
                            .addComponent(jLabel_contrasena)
                            .addComponent(jLabel_puesto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_departamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_nombre)
                        .addGap(68, 68, 68)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_departamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_apellidos)
                            .addComponent(jTextField_nombre)
                            .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_puesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_departamento))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_puesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_contrasena))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 550, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton jButton_Atras;
    public javax.swing.JButton jButton_logout;
    public javax.swing.JButton jButton_registrarse;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_contrasena;
    private javax.swing.JLabel jLabel_departamento;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_puesto;
    public javax.swing.JLabel jLabel_usuarioLogueado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField_apellidos;
    public javax.swing.JTextField jTextField_contrasena;
    public javax.swing.JTextField jTextField_departamento;
    public javax.swing.JTextField jTextField_dni;
    public javax.swing.JTextField jTextField_email;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_puesto;
    // End of variables declaration//GEN-END:variables
}
