/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sara_
 */
public class PantallaRestaurarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRestaurarContrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jButton_restaurar = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel_usuario = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jTextField_dni = new javax.swing.JTextField();
        jLabel_dni = new javax.swing.JLabel();
        jLabel_contrasena_nueva = new javax.swing.JLabel();
        jTextField_contrasena_nueva = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setPreferredSize(new java.awt.Dimension(730, 447));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_restaurar.setBackground(new java.awt.Color(0, 51, 51));
        jButton_restaurar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton_restaurar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restaurar.setText("Restaurar");
        jButton_restaurar.setAlignmentY(0.0F);
        jButton_restaurar.setBorder(null);
        jButton_restaurar.setBorderPainted(false);
        jButton_restaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_restaurar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bg.add(jButton_restaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 36));

        jButton_Atras.setBackground(new java.awt.Color(0, 51, 51));
        jButton_Atras.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("Atrás");
        jButton_Atras.setBorder(null);
        jButton_Atras.setBorderPainted(false);
        jButton_Atras.setPreferredSize(new java.awt.Dimension(110, 30));
        bg.add(jButton_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Contraseña");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 480, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_usuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_usuario.setText("Usuario (email):");

        jTextField_usuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextField_dni.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel_dni.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_dni.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_dni.setText("DNI:");

        jLabel_contrasena_nueva.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_contrasena_nueva.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_contrasena_nueva.setText("Nueva contraseña:");

        jTextField_contrasena_nueva.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_usuario)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_dni)
                        .addGap(106, 106, 106)
                        .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_contrasena_nueva)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_contrasena_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_usuario))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dni))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_contrasena_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_contrasena_nueva))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 550, 450));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 450));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton jButton_Atras;
    public javax.swing.JButton jButton_restaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_contrasena_nueva;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField_contrasena_nueva;
    public javax.swing.JTextField jTextField_dni;
    public javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
